#!/bin/bash

# koji work directories
BASEDIR=basedir
OS_NAME=$(uname -s) # Get the operating system name

mkdir $BASEDIR
chmod 777 $BASEDIR

echo "Detected OS: $OS_NAME"

# own it by container's apache
# host doesn't need to have apache installed, so use
# uid instead
if [ "$OS_NAME" = "Linux" ]; then
    echo "Running docker to set ownership..."
    docker run --rm -v $(pwd)/$BASEDIR:/tmp/basedir alpine chown 48:48 /tmp/basedir
elif [ "$OS_NAME" = "Darwin" ]; then
    echo "Running docker to set ownership..."
    docker run --rm -v $(pwd)/$BASEDIR:/tmp/basedir alpine chown 48:48 /tmp/basedir
else
    echo "Unsupported OS for this operation: $OS_NAME"
fi

mkdir db/data
