#!/bin/bash
. config.local

BASEDIR=`pwd`
HOSTIP=`hostname  -I | cut -f 1 -d ' '`

# Create a docker network for koji containers
docker network create koji-dev 2>/dev/null || true

docker run -d --rm --name koji-postgres \
    --network=koji-dev \
    -p 5432:5432 \
    -e POSTGRES_USER=koji \
    -e POSTGRES_DB=koji \
    -e POSTGRES_HOST_AUTH_METHOD=password \
    -e POSTGRES_PASSWORD=mypassword \
    -e DB_SCHEMA=/opt/schemas/schema.sql \
    -v $BASEDIR/db/data:/var/lib/postgresql/data \
    -v $BASEDIR/db:/docker-entrypoint-initdb.d \
    -v $CODEDIR:/opt \
    docker.io/library/postgres:17 && sleep 2

docker run -it --rm \
    --network=koji-dev \
    -p 8080:80 \
    -p 8081:443 \
    -v $BASEDIR/basedir:/mnt/koji \
    -v $BASEDIR/hub:/opt/cfg \
    -v $CODEDIR:/opt/koji \
    --name koji-hub \
    --env=HOSTIP=$HOSTIP \
    koji \
    /opt/cfg/entrypoint.sh
